FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app

# Copy the pre-built jar from local build directory
COPY api-gateway/build/libs/*SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-Xmx1G", "-jar", "app.jar"]
