server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway
  docker:
    compose:
      enabled: false
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Base Service Routes (for OpenAPI aggregation)
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account-service/**
          filters:
            - RewritePath=/account-service/(?<path>.*), /$\{path}
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/ticket-service/**
          filters:
            - RewritePath=/ticket-service/(?<path>.*), /$\{path}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<path>.*), /$\{path}
        - id: subway-service
          uri: lb://subway-service
          predicates:
            - Path=/subway-service/**
          filters:
            - RewritePath=/subway-service/(?<path>.*), /$\{path}

        # Account Service Routes
        - id: account-service-vouchers
          uri: lb://account-service
          predicates:
            - Path=/vouchers/**
        - id: account-service-accounts
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: account-service-account-discount-packages
          uri: lb://account-service
          predicates:
            - Path=/account-discount-packages/**
        - id: account-service-discount-packages
          uri: lb://account-service
          predicates:
            - Path=/discount-packages/**
        - id: account-service-legacy
          uri: lb://account-service
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<path>.*), /$\{path}

        # Ticket Service Routes
        - id: ticket-service-timed-ticket-plans
          uri: lb://ticket-service
          predicates:
            - Path=/timed-ticket-plans/**
        - id: ticket-service-p2p-journeys
          uri: lb://ticket-service
          predicates:
            - Path=/p2p-journeys/**
        - id: ticket-service-ticket-validations
          uri: lb://ticket-service
          predicates:
            - Path=/ticket-validations/**
        - id: ticket-service-tickets
          uri: lb://ticket-service
          predicates:
            - Path=/tickets/**
        - id: ticket-service-legacy
          uri: lb://ticket-service
          predicates:
            - Path=/ticket/**
          filters:
            - RewritePath=/ticket/(?<path>.*), /$\{path}

        # Order Service Routes
        - id: order-service-payment
          uri: lb://order-service
          predicates:
            - Path=/payment/**
        - id: order-service-orders
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: order-service-legacy
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*), /$\{path}
        - id: order-details-service
          uri: lb://order-service
          predicates:
            - Path=/order-details/**

        # Subway Service Routes
        - id: subway-service-lines
          uri: lb://subway-service
          predicates:
            - Path=/lines/**
          filters:
            - RewritePath=/lines/(?<path>.*), /$\{path}
        - id: subway-service-stations
          uri: lb://subway-service
          predicates:
            - Path=/stations/**
          filters:
            - RewritePath=/stations/(?<path>.*), /$\{path}
        - id: subway-service-legacy
          uri: lb://subway-service
          predicates:
            - Path=/subway/**
          filters:
            - RewritePath=/subway/(?<path>.*), /$\{path}

        # OpenAPI Documentation Routes
        - id: openapi-proxy
          uri: http://api-gateway.metroll:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: openapi-local
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

metroll:
  exception:
    log: true

  auth:
    fake-firebase-profiles: false

springdoc:
  cache:
    disabled: true
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
    server-url: https://metroll.southeastasia.cloudapp.azure.com
  # Configure servers for production deployment
  api-docs:
    servers:
      - url: https://metroll.southeastasia.cloudapp.azure.com
        description: Production Server (HTTPS)
      - url: http://localhost:8080  
        description: Development Server
  show-actuator: true
  
  # Override default server generation
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

eureka:
  client:
    service-url:
      defaultZone: http://service-registry.metroll:8761/eureka/
    register-with-eureka: true
    fetch-registry: true 