spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true

  docker:
    compose:
      enabled: false

  jackson:
    default-property-inclusion: non_null

  data:
    mongodb:
      uri: ${DATABASE_ORDER_SERVICE}
      ssl: {enabled: true}

  rabbitmq:
    host: ${CLOUDAMQP_HOST}
    port: ${CLOUDAMQP_PORT}
    username: ${CLOUDAMQP_USERNAME}
    password: ${CLOUDAMQP_PASSWORD}
    publisher-confirms: true
    virtual-host: ${CLOUDAMQP_VHOST}
    ssl:
      enabled: true

server:
  forward-headers-strategy: framework

metroll:
  exception:
    log: true
  payos:
    client-id: ${PAYOS_CLIENT_ID}
    api-key: ${PAYOS_API_KEY}
    checksum-key: ${PAYOS_CHECKSUM_KEY}
    webhook-url: ${PAYOS_WEBHOOK_URL:http://localhost:8080/order/payment/webhook}

springdoc:
  cache:
    disabled: true
  version: '@springdoc.version@'

eureka:
  client:
    service-url:
      defaultZone: http://service-registry.metroll:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
